### ISSUE TITLE
画像を外部サイトから直リンクしている場合、画像の横幅が制御されない

### ISSUE THREAD

**Issue by giginet** [kawazrepos/Kawaz3rd#240]
![](http://gyazo.com/80b60b9264ef60b8f3db18df06fe4d19.png)

このように、gyazoなどから直リンクされてる場合は、はみ出して表示されることがある

``` less
markdown {
  img {
    max-width: 600px;
  }
}
```

などの対応が必要そう
